- host-monitoring/src/action.php
- host-monitoring/src/downtime.ihtml
- host-monitoring/src/index.ihtml
- host-monitoring/src/table.ihtml
- host-monitoring/src/toolbar.php
Apply a new style for action popin
reference #11
> Apply new style for popin

- host-monitoring/src/index.php
Timezone was not used for "Last Check".
> GMT was not used

- host-monitoring/data.js
Like the service-monitoring, a new way to manage the size of the widget.
Clearer and simpler.
> Refacto for more transparency

- host-monitoring/src/export.ihtml
Add previously deleted line break in CSV export
Refs: #28
> fix(export) : Add line break in CSV export

- host-monitoring/src/toolbar.php
#67
Problem about ACL actions is solved.
> fix(ACL): Fix ACL actions #84

- host-monitoring/src/toolbar.php
> debug deletion

- host-monitoring/src/index.php
Last check, Duration and Hard state Duration
Resolve CP7M-80
> feat(widget): better display of datetime columns

- host-monitoring/src/action.php
- host-monitoring/src/export.php
- host-monitoring/src/index.php
- host-monitoring/src/toolbar.php
fix(widget): Undefined variable
refactor(widget): remove manual loading of Smart.class.php file
fix(widget): Undefined index: host_name
> Cp7 m53 ongoing fixes

- host-monitoring/src/export.php
Fix csv export column format. Replace double quotes and add query bind parameters.
> Cp7 m86 fix export column format

- host-monitoring/src/index.php
Add more protocols to the regex to allow working URLs without perpended slashes.
> fix(monitoring): additional action url protocols

- host-monitoring/data.js
- host-monitoring/src/action.php
- host-monitoring/src/downtime.ihtml
- host-monitoring/src/sendCmd.php
> Mon-3133-downtime-fix

- host-monitoring/src/data_js.js
> enh(widgets): use localStorage to keep checked checkboxes during refresh

- host-monitoring/configs.xml
- host-monitoring/data.js
- host-monitoring/src/index.php
- host-monitoring/src/table.ihtml
correct hard state and last hard state wrong format durations
> fix(UI): correct duration columns

- host-monitoring/src/action.php
- host-monitoring/src/downtime.ihtml
- host-monitoring/src/index.ihtml
Fix datepicker DT in the popin
> fix(datepicker): change end date if start date is set after it

- .gitignore
- host-monitoring/configs.xml
- host-monitoring/src/export.php
- host-monitoring/src/index.php
- host-monitoring/src/table.ihtml
> enh(preference): add select2 on severity preference

- host-monitoring/src/toolbar.php
https://github.com/centreon/centreon/pull/8291
param not use in /widgets/host-monitoring/src/action
> fix(security) remove session id parameter 

- host-monitoring/configs.xml
change version number to be able to release a new widget with cherry-picked modifications
> change version number

- host-monitoring/configs.xml
- host-monitoring/index.php
- host-monitoring/src/DB-Func.php
- host-monitoring/src/action.php
- host-monitoring/src/export.php
- host-monitoring/src/index.php
- host-monitoring/src/sendCmd.php
- host-monitoring/src/toolbar.php
- avoid injections from https request parameters
- clean code and style
For :
2.8
> fix(security): avoid injections from http params 

- host-monitoring/index.php
- host-monitoring/src/DB-Func.php
- host-monitoring/src/action.php
- host-monitoring/src/export.php
- host-monitoring/src/index.php
- host-monitoring/src/sendCmd.php
- host-monitoring/src/toolbar.php
- avoid injections from https request parameters
- clean code and style
For :
20.04
19.10
19.04
18.10
> fix(security): avoid injections from http params

- host-monitoring/src/index.php
- host-monitoring/src/table.ihtml
redirect hosts to resource details panel
/!\ waiting https://github.com/centreon/centreon/pull/8984 to be merged
**Fixes** MON-5657
<h2> How this pull request can be tested ? </h2>
Click on a host
==> check redirection to resource panel details of the host
> enh(ui): redirect hosts to resource details panel

- host-monitoring/src/index.php
fix severity display & filtering
**Fixes** MON-5975
> fix(sql): fix severity display & filtering

- host-monitoring/src/toolbar.php
unselect checkbox after sending external command
Replace #93
Refs: MON-5882
thanks @tanguyvda
> fix(ui): unselect checkbox after sending external command

- host-monitoring/configs.xml
> chore(install): update to version 19.10.7

- host-monitoring/configs.xml
> chore(install): set version to 20.04.5

- Jenkinsfile
- host-monitoring/configs.xml
Preparing version 21.04.0 for the widget centren-widget-host-monitoring
> chore(install): update version to 21.04.0

- .gitignore
- Jenkinsfile
- composer.json
- composer.lock
- host-monitoring/index.php
- host-monitoring/src/DB-Func.php
- host-monitoring/src/action.php
- host-monitoring/src/export.php
- host-monitoring/src/index.php
- host-monitoring/src/sendCmd.php
- host-monitoring/src/toolbar.php
- ruleset.xml
- sonar-project.properties
Add requirements to be able to implement githubviolation, sonarQube analysis, coverage and codestyle
**Fixes** # (MON-6425)
linked to : https://github.com/centreon/centreon-build/pull/384
> enh(chore): add CI requirements for github violation

- .github/PULL_REQUEST_TEMPLATE.md
- Jenkinsfile
- composer.json
- host-monitoring/configs.xml
> chore(version): prepare 21.10 serie
